defmodule MetaDsl.Ecto do
  @moduledoc """
  Generator that produces Ecto schema module definitions from MetaDsl
  meta-types.

  `generate/1` accepts either a single `MetaDsl.MetaType` or a list of them
  and returns the corresponding quoted Elixir expression(s).  Each expression
  is a `defmodule` block whose name is the CamelCase version of the meta-type
  atom — no extra namespace is added, so the schemas are naturally nested
  inside whichever module calls the generator.

  The generated module calls `use Ecto.Schema` and wraps all field declarations
  in a `schema/2` block.  The table name is the snake_case plural of the
  meta-type atom by default (e.g. `:user` → `"users"`).

  ## Type mapping

  MetaDsl types are mapped to Ecto types as follows:

  | MetaDsl type        | Ecto type          |
  |---------------------|--------------------|
  | `:string`           | `:string`          |
  | `:integer`          | `:integer`         |
  | `:float`            | `:float`           |
  | `:boolean`          | `:boolean`         |
  | `:uuid`             | `:binary_id`       |
  | `:decimal`          | `:decimal`         |
  | `:date`             | `:date`            |
  | `:time`             | `:time`            |
  | `:datetime`         | `:utc_datetime`    |
  | `:naive_datetime`   | `:naive_datetime`  |
  | `:map`              | `:map`             |
  | `{:list, inner}`    | `{:array, inner}`  |
  | anything else       | passed through     |

  ## Annotations

  The following annotations are recognised by the generator:

  ### Per-type annotations (on `MetaDsl.MetaType`)

  * `:table` — override the Ecto table name (string).
  * `:timestamps` — when `true`, appends a `timestamps()` call inside the
    schema block.

  ### Per-property annotations (on `MetaDsl.Property`)

  * `:ecto_type` — override the mapped Ecto field type for this property.

  ## Compile-time usage via `use`

  The most common usage is to `use` the generator inside a module, pointing it
  at a schema.  All types are generated by default; pass `type:` (atom or list
  of atoms) to generate only a subset.  Schemas are automatically nested
  inside the calling module — no explicit namespace is required.

      defmodule MyApp.Schema do
        use MetaDsl

        meta_type :user do
          property :id,    :uuid,   required: true
          property :name,  :string, required: true
          property :email, :string, required: true
        end

        subtype :public_user, from: :user, only: [:id, :name]
      end

      # All types — defines MyApp.Models.User and MyApp.Models.PublicUser
      defmodule MyApp.Models do
        use MetaDsl.Ecto, schema: MyApp.Schema
      end

      # Single type — defines MyApp.Models.User only
      defmodule MyApp.Models do
        use MetaDsl.Ecto, schema: MyApp.Schema, type: :user
      end

      # Subset of types
      defmodule MyApp.Models do
        use MetaDsl.Ecto, schema: MyApp.Schema, type: [:user, :public_user]
      end

  ## Functional usage

      # All types at once — returns a list of quoted expressions
      asts = MyApp.Schema.meta_types() |> MetaDsl.Ecto.generate()

      # Single type — returns a single quoted expression
      ast = MyApp.Schema.meta_type(:user) |> MetaDsl.Ecto.generate()
  """

  @doc """
  Generates quoted Ecto schema definition(s) from a `MetaDsl.MetaType` or a
  list of `MetaDsl.MetaType` structs.

  - Given a **single** `MetaDsl.MetaType`, returns a single quoted expression.
  - Given a **list**, returns a list of quoted expressions.

  Each expression is a `defmodule` block whose name is the CamelCase atom
  with no extra namespace prefix, so it composes naturally with Elixir's own
  module nesting.
  """
  @spec generate(MetaDsl.MetaType.t()) :: Macro.t()
  @spec generate([MetaDsl.MetaType.t()]) :: [Macro.t()]
  def generate(%MetaDsl.MetaType{} = meta_type) do
    generate_schema(meta_type, nil)
  end

  def generate(meta_types) when is_list(meta_types) do
    Enum.map(meta_types, &generate_schema(&1, nil))
  end

  @doc false
  defmacro __using__(opts) do
    schema = Keyword.fetch!(opts, :schema)
    schema_module = Macro.expand(schema, __CALLER__)
    type_filter = Keyword.get(opts, :type, nil)
    namespace = __CALLER__.module

    all_types = schema_module.meta_types()

    types =
      case type_filter do
        nil ->
          all_types

        name when is_atom(name) ->
          case Enum.find(all_types, &(&1.name == name)) do
            nil ->
              raise ArgumentError,
                    "MetaDsl.Ecto: unknown type #{inspect(name)} in schema #{inspect(schema_module)}"

            type ->
              [type]
          end

        names when is_list(names) ->
          known = MapSet.new(all_types, & &1.name)
          missing = Enum.reject(names, &MapSet.member?(known, &1))

          if missing != [] do
            raise ArgumentError,
                  "MetaDsl.Ecto: unknown types #{inspect(missing)} in schema #{inspect(schema_module)}"
          end

          Enum.filter(all_types, &(&1.name in names))
      end

    asts = Enum.map(types, &generate_schema(&1, namespace))

    quote do
      unquote_splicing(asts)
    end
  end

  # ---------------------------------------------------------------------------
  # Private helpers
  # ---------------------------------------------------------------------------

  defp generate_schema(
         %MetaDsl.MetaType{name: name, properties: properties, annotations: annotations},
         namespace
       ) do
    module_name = build_module_name(name, namespace)
    table_name = Map.get(annotations, :table, default_table_name(name))
    include_timestamps = Map.get(annotations, :timestamps, false)

    field_asts = Enum.map(properties, &build_field_ast/1)

    schema_body =
      if include_timestamps do
        field_asts ++
          [
            quote do
              timestamps()
            end
          ]
      else
        field_asts
      end

    quote do
      defmodule unquote(module_name) do
        use Ecto.Schema

        schema unquote(table_name) do
          unquote_splicing(schema_body)
        end
      end
    end
  end

  defp build_field_ast(%MetaDsl.Property{name: field_name, type: type, annotations: annotations}) do
    ecto_type = Map.get(annotations, :ecto_type, map_type(type))

    quote do
      field(unquote(field_name), unquote(ecto_type))
    end
  end

  defp default_table_name(name) do
    name
    |> Atom.to_string()
    |> Kernel.<>("s")
  end

  defp map_type(:string), do: :string
  defp map_type(:integer), do: :integer
  defp map_type(:float), do: :float
  defp map_type(:boolean), do: :boolean
  defp map_type(:uuid), do: :binary_id
  defp map_type(:decimal), do: :decimal
  defp map_type(:date), do: :date
  defp map_type(:time), do: :time
  defp map_type(:datetime), do: :utc_datetime
  defp map_type(:naive_datetime), do: :naive_datetime
  defp map_type(:map), do: :map
  defp map_type({:list, inner}), do: {:array, map_type(inner)}
  defp map_type(other), do: other

  defp build_module_name(name, nil) do
    name
    |> Atom.to_string()
    |> Macro.camelize()
    |> then(&Module.concat([&1]))
  end

  defp build_module_name(name, namespace) do
    name
    |> Atom.to_string()
    |> Macro.camelize()
    |> then(&Module.concat(namespace, &1))
  end
end
