defmodule MetaDsl.Validation do
  @moduledoc """
  Generator that produces validation modules from MetaDsl meta-types.

  `generate/1` accepts either a single `MetaDsl.MetaType` or a list of them
  and returns the corresponding quoted Elixir expression(s).  Each expression
  is a `defmodule` block whose name is the CamelCase version of the meta-type
  atom — no extra namespace is added, so the validators are naturally nested
  inside whichever module calls the generator.

  Each generated module exposes a single `validate/1` function that accepts a
  map or struct and returns `{:ok, data}` when all field validations pass, or
  `{:error, errors}` where `errors` is a list of `{field, reason}` tuples in
  property-declaration order.

  ## Custom validators

  Each property can carry a `:validate` annotation with a function that
  accepts the field value and returns one of:

    * `:ok`, `{:ok, _}`, or `true` — the value is valid.
    * `{:error, reason}` — the value is invalid; `reason` is included in the
      error tuple.
    * `false` — the value is invalid; the default `"is invalid"` message is
      used.

  The annotation is an extra option on the `property` declaration:

      meta_type :user do
        property :email, :string, validate: fn v ->
          if is_binary(v) and String.contains?(v, "@"),
            do: :ok,
            else: {:error, "must be a valid email"}
        end
      end

  When a property has both `required: true` and a `:validate` annotation, the
  nil-presence check runs first; the custom validator is only called when the
  value is non-`nil`.

  When no `:validate` annotation is present, the only check for required fields
  is the nil-presence check.

  ## Compile-time usage via `use`

  The most common usage is to `use` the generator inside a module, pointing it
  at a schema.  All types are generated by default; pass `type:` (atom or list
  of atoms) to generate only a subset.  Validators are automatically nested
  inside the calling module — no explicit namespace is required.

      defmodule MyApp.Schema do
        use MetaDsl

        meta_type :user do
          property :id,   :uuid,   required: true
          property :name, :string, required: true
          property :role, :string, default: "member"
        end

        subtype :public_user, from: :user, only: [:id, :name]
      end

      # All types — defines MyApp.Validators.User and MyApp.Validators.PublicUser
      defmodule MyApp.Validators do
        use MetaDsl.Validation, schema: MyApp.Schema
      end

      # Single type — defines MyApp.Validators.User only
      defmodule MyApp.Validators do
        use MetaDsl.Validation, schema: MyApp.Schema, type: :user
      end

      # Subset of types
      defmodule MyApp.Validators do
        use MetaDsl.Validation, schema: MyApp.Schema, type: [:user, :public_user]
      end

  ## Functional usage

      # All types at once — returns a list of quoted expressions
      asts = MyApp.Schema.meta_types() |> MetaDsl.Validation.generate()

      # Single type — returns a single quoted expression
      ast = MyApp.Schema.meta_type(:user) |> MetaDsl.Validation.generate()
  """

  @doc """
  Generates quoted Elixir validator module definition(s) from a
  `MetaDsl.MetaType` or a list of `MetaDsl.MetaType` structs.

  - Given a **single** `MetaDsl.MetaType`, returns a single quoted expression.
  - Given a **list**, returns a list of quoted expressions.

  Each expression is a `defmodule` block whose name is the CamelCase atom
  with no extra namespace prefix, so it composes naturally with Elixir's own
  module nesting.
  """
  @spec generate(MetaDsl.MetaType.t()) :: Macro.t()
  @spec generate([MetaDsl.MetaType.t()]) :: [Macro.t()]
  def generate(%MetaDsl.MetaType{} = meta_type) do
    generate_validator(meta_type, nil)
  end

  def generate(meta_types) when is_list(meta_types) do
    Enum.map(meta_types, &generate_validator(&1, nil))
  end

  @doc false
  defmacro __using__(opts) do
    schema = Keyword.fetch!(opts, :schema)
    schema_module = Macro.expand(schema, __CALLER__)
    type_filter = Keyword.get(opts, :type, nil)
    namespace = __CALLER__.module

    all_types = schema_module.meta_types()

    types =
      case type_filter do
        nil ->
          all_types

        name when is_atom(name) ->
          case Enum.find(all_types, &(&1.name == name)) do
            nil ->
              raise ArgumentError,
                    "MetaDsl.Validation: unknown type #{inspect(name)} in schema #{inspect(schema_module)}"

            type ->
              [type]
          end

        names when is_list(names) ->
          known = MapSet.new(all_types, & &1.name)
          missing = Enum.reject(names, &MapSet.member?(known, &1))

          if missing != [] do
            raise ArgumentError,
                  "MetaDsl.Validation: unknown types #{inspect(missing)} in schema #{inspect(schema_module)}"
          end

          Enum.filter(all_types, &(&1.name in names))
      end

    asts = Enum.map(types, &generate_validator(&1, namespace))

    quote do
      unquote_splicing(asts)
    end
  end

  # ---------------------------------------------------------------------------
  # Private helpers
  # ---------------------------------------------------------------------------

  defp generate_validator(%MetaDsl.MetaType{name: name, properties: properties}, namespace) do
    module_name = build_module_name(name, namespace)
    errors_var = Macro.var(:errors, nil)
    data_var = Macro.var(:data, nil)

    checks =
      properties
      |> Enum.map(&property_check_ast(&1, errors_var, data_var))
      |> Enum.reject(&is_nil/1)

    quote do
      defmodule unquote(module_name) do
        def validate(unquote(data_var)) do
          unquote(errors_var) = []
          unquote_splicing(checks)

          if unquote(errors_var) == [] do
            {:ok, unquote(data_var)}
          else
            {:error, Enum.reverse(unquote(errors_var))}
          end
        end
      end
    end
  end

  # Builds a single AST statement that updates `errors_var` for one property.
  # Returns nil when no validation is needed (optional field, no custom validator).
  defp property_check_ast(
         %MetaDsl.Property{name: field, required: required, annotations: annotations},
         errors_var,
         data_var
       ) do
    validator = Map.get(annotations, :validate)
    quoted_validator = quote_validator(validator)

    cond do
      validator != nil && required ->
        # Nil-presence check first; custom validator runs only on non-nil values.
        quote do
          unquote(errors_var) =
            case Map.get(unquote(data_var), unquote(field)) do
              nil ->
                [{unquote(field), "is required"} | unquote(errors_var)]

              value ->
                case unquote(quoted_validator).(value) do
                  :ok -> unquote(errors_var)
                  {:ok, _} -> unquote(errors_var)
                  true -> unquote(errors_var)
                  false -> [{unquote(field), "is invalid"} | unquote(errors_var)]
                  {:error, reason} -> [{unquote(field), reason} | unquote(errors_var)]
                end
            end
        end

      validator != nil ->
        # Optional field with a custom validator — always call the validator.
        quote do
          unquote(errors_var) =
            case unquote(quoted_validator).(Map.get(unquote(data_var), unquote(field))) do
              :ok -> unquote(errors_var)
              {:ok, _} -> unquote(errors_var)
              true -> unquote(errors_var)
              false -> [{unquote(field), "is invalid"} | unquote(errors_var)]
              {:error, reason} -> [{unquote(field), reason} | unquote(errors_var)]
            end
        end

      required ->
        # Required field, no custom validator — nil-presence check only.
        quote do
          unquote(errors_var) =
            if Map.get(unquote(data_var), unquote(field)) == nil do
              [{unquote(field), "is required"} | unquote(errors_var)]
            else
              unquote(errors_var)
            end
        end

      true ->
        nil
    end
  end

  # When the annotation value is an actual function (functional-usage path),
  # serialize it to a binary literal so it can be embedded in generated AST.
  # Any Erlang term, including anonymous function closures, can be serialised
  # with :erlang.term_to_binary and restored with :erlang.binary_to_term.
  # When the value is already an AST node (DSL macro path), use it directly.
  defp quote_validator(validator) when is_function(validator) do
    binary = :erlang.term_to_binary(validator)
    quote do: :erlang.binary_to_term(unquote(binary))
  end

  defp quote_validator(validator), do: validator

  defp build_module_name(name, nil) do
    name
    |> Atom.to_string()
    |> Macro.camelize()
    |> then(&Module.concat([&1]))
  end

  defp build_module_name(name, namespace) do
    name
    |> Atom.to_string()
    |> Macro.camelize()
    |> then(&Module.concat(namespace, &1))
  end
end
