defmodule MetaDsl.Validation do
  @moduledoc """
  Generator that produces validation modules from MetaDsl meta-types.

  `generate/1` accepts either a single `MetaDsl.MetaType` or a list of them
  and returns the corresponding quoted Elixir expression(s).  Each expression
  is a `defmodule` block whose name is the CamelCase version of the meta-type
  atom — no extra namespace is added, so the validators are naturally nested
  inside whichever module calls the generator.

  Each generated module exposes a single `validate/1` function that accepts a
  map or struct and returns `{:ok, data}` when all required fields are present
  and non-`nil`, or `{:error, errors}` where `errors` is a list of
  `{field, reason}` tuples for every required field that is missing.

  ## Compile-time usage via `use`

  The most common usage is to `use` the generator inside a module, pointing it
  at a schema.  All types are generated by default; pass `type:` (atom or list
  of atoms) to generate only a subset.  Validators are automatically nested
  inside the calling module — no explicit namespace is required.

      defmodule MyApp.Schema do
        use MetaDsl

        meta_type :user do
          property :id,   :uuid,   required: true
          property :name, :string, required: true
          property :role, :string, default: "member"
        end

        subtype :public_user, from: :user, only: [:id, :name]
      end

      # All types — defines MyApp.Validators.User and MyApp.Validators.PublicUser
      defmodule MyApp.Validators do
        use MetaDsl.Validation, schema: MyApp.Schema
      end

      # Single type — defines MyApp.Validators.User only
      defmodule MyApp.Validators do
        use MetaDsl.Validation, schema: MyApp.Schema, type: :user
      end

      # Subset of types
      defmodule MyApp.Validators do
        use MetaDsl.Validation, schema: MyApp.Schema, type: [:user, :public_user]
      end

  ## Functional usage

      # All types at once — returns a list of quoted expressions
      asts = MyApp.Schema.meta_types() |> MetaDsl.Validation.generate()

      # Single type — returns a single quoted expression
      ast = MyApp.Schema.meta_type(:user) |> MetaDsl.Validation.generate()
  """

  @doc """
  Generates quoted Elixir validator module definition(s) from a
  `MetaDsl.MetaType` or a list of `MetaDsl.MetaType` structs.

  - Given a **single** `MetaDsl.MetaType`, returns a single quoted expression.
  - Given a **list**, returns a list of quoted expressions.

  Each expression is a `defmodule` block whose name is the CamelCase atom
  with no extra namespace prefix, so it composes naturally with Elixir's own
  module nesting.
  """
  @spec generate(MetaDsl.MetaType.t()) :: Macro.t()
  @spec generate([MetaDsl.MetaType.t()]) :: [Macro.t()]
  def generate(%MetaDsl.MetaType{} = meta_type) do
    generate_validator(meta_type, nil)
  end

  def generate(meta_types) when is_list(meta_types) do
    Enum.map(meta_types, &generate_validator(&1, nil))
  end

  @doc false
  defmacro __using__(opts) do
    schema = Keyword.fetch!(opts, :schema)
    schema_module = Macro.expand(schema, __CALLER__)
    type_filter = Keyword.get(opts, :type, nil)
    namespace = __CALLER__.module

    all_types = schema_module.meta_types()

    types =
      case type_filter do
        nil ->
          all_types

        name when is_atom(name) ->
          case Enum.find(all_types, &(&1.name == name)) do
            nil ->
              raise ArgumentError,
                    "MetaDsl.Validation: unknown type #{inspect(name)} in schema #{inspect(schema_module)}"

            type ->
              [type]
          end

        names when is_list(names) ->
          known = MapSet.new(all_types, & &1.name)
          missing = Enum.reject(names, &MapSet.member?(known, &1))

          if missing != [] do
            raise ArgumentError,
                  "MetaDsl.Validation: unknown types #{inspect(missing)} in schema #{inspect(schema_module)}"
          end

          Enum.filter(all_types, &(&1.name in names))
      end

    asts = Enum.map(types, &generate_validator(&1, namespace))

    quote do
      unquote_splicing(asts)
    end
  end

  # ---------------------------------------------------------------------------
  # Private helpers
  # ---------------------------------------------------------------------------

  defp generate_validator(%MetaDsl.MetaType{name: name, properties: properties}, namespace) do
    module_name = build_module_name(name, namespace)
    required_fields = properties |> Enum.filter(& &1.required) |> Enum.map(& &1.name)

    quote do
      defmodule unquote(module_name) do
        def validate(data) do
          errors =
            Enum.reduce(unquote(required_fields), [], fn field, acc ->
              if Map.get(data, field) == nil do
                [{field, "is required"} | acc]
              else
                acc
              end
            end)

          if errors == [] do
            {:ok, data}
          else
            {:error, Enum.reverse(errors)}
          end
        end
      end
    end
  end

  defp build_module_name(name, nil) do
    name
    |> Atom.to_string()
    |> Macro.camelize()
    |> then(&Module.concat([&1]))
  end

  defp build_module_name(name, namespace) do
    name
    |> Atom.to_string()
    |> Macro.camelize()
    |> then(&Module.concat(namespace, &1))
  end
end
