defmodule MetaDsl.Generators.ElixirStructs do
  @moduledoc """
  Generator that produces Elixir struct module definitions from MetaDsl
  meta-types.

  `generate/1` accepts either a single `MetaDsl.MetaType` or a list of them
  and returns the corresponding quoted Elixir expression(s).  Each expression
  is a `defmodule` block whose name is the CamelCase version of the meta-type
  atom — no extra namespace is added, so the structs are naturally nested
  inside whichever module calls the generator.

  Required properties are reflected as `@enforce_keys`; optional properties
  with a non-`nil` default carry that default into the `defstruct` field list.

  ## Compile-time usage via `use`

  The most common usage is to `use` the generator inside a module, pointing it
  at a schema.  All types are generated by default; pass `type:` (atom or list
  of atoms) to generate only a subset.  Structs are automatically nested
  inside the calling module — no explicit namespace is required.

      defmodule MyApp.Schema do
        use MetaDsl

        meta_type :user do
          property :id,   :uuid,   required: true
          property :name, :string, required: true
          property :role, :string, default: "member"
        end

        subtype :public_user, from: :user, only: [:id, :name]
      end

      # All types — defines MyApp.Structs.User and MyApp.Structs.PublicUser
      defmodule MyApp.Structs do
        use MetaDsl.Generators.ElixirStructs, schema: MyApp.Schema
      end

      # Single type — defines MyApp.Structs.User only
      defmodule MyApp.Structs do
        use MetaDsl.Generators.ElixirStructs, schema: MyApp.Schema, type: :user
      end

      # Subset of types
      defmodule MyApp.Structs do
        use MetaDsl.Generators.ElixirStructs, schema: MyApp.Schema, type: [:user, :public_user]
      end

  ## Functional usage

      # All types at once — returns a list of quoted expressions
      asts = MyApp.Schema.meta_types() |> MetaDsl.Generators.ElixirStructs.generate()

      # Single type — returns a single quoted expression
      ast = MyApp.Schema.meta_type(:user) |> MetaDsl.Generators.ElixirStructs.generate()
  """

  @doc """
  Generates quoted Elixir struct definition(s) from a `MetaDsl.MetaType` or a
  list of `MetaDsl.MetaType` structs.

  - Given a **single** `MetaDsl.MetaType`, returns a single quoted expression.
  - Given a **list**, returns a list of quoted expressions.

  Each expression is a `defmodule` block whose name is the CamelCase atom
  with no extra namespace prefix, so it composes naturally with Elixir's own
  module nesting.
  """
  @spec generate(MetaDsl.MetaType.t()) :: Macro.t()
  @spec generate([MetaDsl.MetaType.t()]) :: [Macro.t()]
  def generate(%MetaDsl.MetaType{} = meta_type) do
    generate_struct(meta_type, nil)
  end

  def generate(meta_types) when is_list(meta_types) do
    Enum.map(meta_types, &generate_struct(&1, nil))
  end

  @doc false
  defmacro __using__(opts) do
    schema = Keyword.fetch!(opts, :schema)
    schema_module = Macro.expand(schema, __CALLER__)
    type_filter = Keyword.get(opts, :type, nil)
    namespace = __CALLER__.module

    all_types = schema_module.meta_types()

    types =
      case type_filter do
        nil -> all_types
        name when is_atom(name) -> Enum.filter(all_types, &(&1.name == name))
        names when is_list(names) -> Enum.filter(all_types, &(&1.name in names))
      end

    asts = Enum.map(types, &generate_struct(&1, namespace))

    quote do
      unquote_splicing(asts)
    end
  end

  # ---------------------------------------------------------------------------
  # Private helpers
  # ---------------------------------------------------------------------------

  defp generate_struct(%MetaDsl.MetaType{name: name, properties: properties}, namespace) do
    module_name = build_module_name(name, namespace)
    enforce_keys = properties |> Enum.filter(& &1.required) |> Enum.map(& &1.name)
    struct_fields = build_struct_fields(properties)

    if Enum.empty?(enforce_keys) do
      quote do
        defmodule unquote(module_name) do
          defstruct unquote(struct_fields)
        end
      end
    else
      quote do
        defmodule unquote(module_name) do
          @enforce_keys unquote(enforce_keys)
          defstruct unquote(struct_fields)
        end
      end
    end
  end

  defp build_module_name(name, nil) do
    name
    |> Atom.to_string()
    |> Macro.camelize()
    |> then(&Module.concat([&1]))
  end

  defp build_module_name(name, namespace) do
    name
    |> Atom.to_string()
    |> Macro.camelize()
    |> then(&Module.concat(namespace, &1))
  end

  defp build_struct_fields(properties) do
    Enum.map(properties, fn
      %MetaDsl.Property{name: name, default: nil} -> name
      %MetaDsl.Property{name: name, default: default} -> {name, default}
    end)
  end
end
